### PR TITLE
Optional Chaining RFC

### PR DESCRIPTION
**Pull request by solomon-b**
RFC For Optional Chaining. Please discuss in associated [issue](https://github.com/hasura/kriti-lang/issues/30).

[rendered](https://github.com/hasura/kriti-lang/blob/RFC/optional-chaining/RFCs/OptionalChaining.md)

### CODE REVIEW

**Comment by sordina** [comment]
Absolutely.

**Review by sordina — APPROVED** [review]
This makes total sense and there's a lot of precedent for an operator like this. I think it would be very valuable to at some point have editor support for schemas so that the decision to use these kinds of operators could be made automatically but that's something to think about in the future.

**Comment by motleydev** [comment]
LGTM, I would opt not to allow null or exception to be an implementation switch. That seems like it would lead to a lack of knowledge and code transference depending on how it was implemented in each toolchain.

**Comment by jkachmar** [comment]
+1 to this; i think the fact that we can pretty much directly pull syntax/semantics for this operator from prior art in the JS, C#, etc. ecosystems means that we should be able to proceed without a much more involved RFC than what you've written up here solomon.

**Review by jkachmar — APPROVED** [review]

**Comment by solomon-b** [comment]
Thanks for the feedback everyone! I'll go ahead and merge this now.

**Pull request merged**
