### PR TITLE
Exending Operators RFC

### PR DESCRIPTION
**Pull request by solomon-b**
RFC for Addtional operators and operator semantic changes. Please discuss in associated [issue](https://github.com/hasura/kriti-lang/issues/38).

[rendered](https://github.com/hasura/kriti-lang/blob/RFC/extend-operator-availability/RFCs/ExtendOperatorAvailability.md)

### CODE REVIEW

**Comment by sordina** [comment]
From my comment on the issue:

> Yes this makes total sense to me. I think we only added the if-statement restriction in order to be conservative, but it makes things more verbose and less intuitive.

**Review by sordina — APPROVED** [review]
The only possible issue I can think of is that some JSON literals could potentially conflict with some expressions in the future but none immediately spring to mind. As long as we have test-coverage to ensure that's not the case I think this should be an easy win.

**Comment by jkachmar** [comment]
> `escapeUri "foo+!"`

This is the only thing I'm somewhat confused by within the RFC.

What's the new functionality supported here that wasn't present before?

So far as I can tell, this should just be a string that is escaped right?

**Comment by solomon-b** [comment]
> > `escapeUri "foo+!"`
> 
> This is the only thing I'm somewhat confused by within the RFC.
> 
> What's the new functionality supported here that wasn't present before?
> 
> So far as I can tell, this should just be a string that is escaped right?

Currently you need to wrap the function call in braces, eg; 
```
{ "bar": {{ escapeUrl "foo+!" }} }
```
The proposal would change this to:
```
{ "bar": escapeUrl "foo+!"  }
```

**Comment by solomon-b** [comment]
The new operators are merged. This leaves the more constroversial parts of this RFC:

1. Do we allow operators outside of `If` predicates?
2. Do we remove the double curly brackets from operators, functions, and path lookups?
3. Do we replace the `if` syntax with a ternary operator?
4. Do we replace `range` with `map` or some more terse look syntax?

**Comment by solomon-b** [comment]
Actually, I'm thinking more about all of this and I think this RFC is now a little too vague. I'm closing this and will write one or two new ones and a few sub issues those remaining questions fall into.

**Pull request closed without merging**
