### PR TITLE
New KritiFunc functions

### PR DESCRIPTION
**Pull request by sordina**
This introduces some new functions and helpers.

Added `parserToFunc` helper to allow conversion from Aeson FromJson parsers to KritiFuncs. This should allow most current function implementations to be defined in terms of Aeson Parsers and if we switch to a richer KritiFunc representation then we will only need to change the definition of `parserToFunc`.

New functions: (Naming inspired by https://ramdajs.com/docs/)

* toPairs
* fromPairs
* removeNulls 
* concat
* parserToFunc

### CODE REVIEW

**Review by codedmart — APPROVED** [review]
LGTM :+1:

**Comment by codedmart** [comment]
@sordina I forgot to ask in the review, but does the changelog need updated?

**Comment by sordina** [comment]
> @sordina I forgot to ask in the review, but does the changelog need updated?

Done!

**Comment by solomon-b** [comment]
All of these functions look fine. My only question is if we should look to some standard library our user base will be familiar with, such as Lodash or Ramda, to crib the functions we include in our "standard lib"?

For example, both ramda and lodash use the name `fromPairs` for `arrayToObject`.

**Comment by sordina** [comment]
> All of these functions look fine. My only question is if we should look to some standard library our user base will be familiar with, such as Lodash or Ramda, to crib the functions/names we include in our "standard lib"?
> 
> For example, both ramda and lodash use the name `fromPairs` for `arrayToObject`.

Yeah I was thinking the same thing. The main issue is a lot of those libraries use lambdas, so we might have to find inspiration from somewhere oldschool.

**Comment by solomon-b** [comment]
How about the python standard lib?

**Comment by sordina** [comment]
> How about the python standard lib?

I think Python mostly uses splatting for this kind of thing so might not have a lot of similar functions.

**Comment by sordina** [comment]
@solomon-b I've updated the defined function in basicFuncMap to match the naming from https://ramdajs.com/docs/ where they can.

**Comment by solomon-b** [comment]
Looks great!

**Pull request merged**
